ur10e:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - tool_taotong

    gains:
      shoulder_pan_joint: { p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0 }
      shoulder_lift_joint: { p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0 }
      elbow_joint: { p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0 }
      wrist_1_joint: { p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0 }
      wrist_2_joint: { p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0 }
      wrist_3_joint: { p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0 }
      tool_taotong: { p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0 }
