controller_manager_ns: ''
  controller_list:
    - name: rokae/arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - xmate_joint_1
        - xmate_joint_2
        - xmate_joint_3
        - xmate_joint_4
        - xmate_joint_5
        - xmate_joint_6
        - xmate_joint_7
      gains:
          xmate_joint_1:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          xmate_joint_2:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          xmate_joint_3:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          xmate_joint_4:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          xmate_joint_5:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          xmate_joint_6:
            p: 100
            d: 1
            i: 1
            i_clamp: 1
          xmate_joint_7:
            p: 100
            d: 1
            i: 1
            i_clamp: 1

    - name: rokae/hand_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - tool_taotong
      gains:
        tool_taotong:
          p: 100
          d: 1
          i: 1
          i_clamp: 1
        
